from base.message_format import MessageFormat

class Formats:
    MESSAGE = MessageFormat({
        'message_id': str, 
        'message_type': str, 
        'data': dict
    })
    """
    message_id: the id of request, usually generated by uuid4.\n
    message_type: the type of message. See Words\n
    data: keys are parameters, values are corresponding values.\n
    """

class Words:
    class MessageType:
        REQUEST = 'request'
        RESPONSE = 'response'
        EVENT = 'event'
        HANDSHAKE = 'handshake'
        HEARTBEAT = 'heartbeat'
    class Command:
        SYNC_LOBBY_STATUS = 'sync_lobby_status'
        GET_PLAYER_ROOM_STATUS = 'get_player_room_status'
        CHECK_MY_WORKS = 'check_my_works'
        CHECK_DEV_WORKS = 'check_dev_works'
        LOGIN = 'login'
        LOGOUT = 'logout'
        REGISTER = 'register'
        EXIT = 'exit'
        UPLOAD_START = 'upload_start'
        UPLOAD_END = 'upload_end'
        DOWNLOAD_START = 'download_start'
        CHECK_GAME_VALID = 'check_game_valid'
        CHECK_STORE = 'check_store'
        CREATE_ROOM = 'create_room'
        JOIN_ROOM = 'join_room'
        LEAVE_ROOM = 'leave_room'
        START_GAME = 'start_game'
    class EventName:
        PLAYER_ONLINE = 'player_online'
        PLAYER_OFFLINE = 'player_offline'
        GAME_FETCHED = 'game_fetched'
        GAME_STARTED = 'game_started'
        ROOM_UPDATED = 'room_updated'
    class DataKeys:
        PARAMS = 'params'
        class Handshake:
            ROLE = 'role'
        class Response:
            RESPONDING_ID = 'responding_id'
            RESULT = 'result'
        class Request:
            COMMAND = 'command'
        class Event:
            EVENT_NAME = 'event_name'
    class ParamKeys:
        class Login:
            USERNAME = 'username'
            PASSWORD = 'password'
        class Logout:
            USERNAME = 'username'
        class Register:
            USERNAME = 'username'
            PASSWORD = 'password'
        class Failure:
            REASON = 'reason'
        class PlayerOnline:
            PLAYER_NAME = 'player_name'
        class PlayerOffline:
            PLAYER_NAME = 'player_name'
        class LobbyStatus:
            ONLINE_PLAYERS = 'online_players'
            ROOMS = 'rooms'
        class Success:
            PORT = 'port'
        class Metadata:
            GAME_ID = 'game_id'
            GAME_NAME = 'game_name'
            VERSION = 'version'
            UPLOADER = 'uploader'
            FILE_NAME = 'file_name'
            SIZE = 'size'
            SHA256 = 'sha256'
            PLAYERS = 'players'
            # for version controling metadata
            ALL_VERSIONS = 'all_versions'
        class StoreStatus:
            GAMES = 'games'
        class CheckInfo:
            USERNAME = 'username'
        class Room:
            ROOM_NAME = 'room_name'
            USERNAME = 'username'
            GAME_ID = 'game_id'
            OWNER = 'owner'
            PLAYER_LIST = 'player_list'
            EXPECTED_PLAYERS = 'expected_players'
            IS_PLAYING = 'is_playing'
            NOW_ROOM_DATA = 'now_room_data'
    class Roles:
        PLAYER = 'player'
        DEVELOPER = 'developer'
        LOBBYSERVER = 'lobbyserver'
        DEVELOPERSERVER = 'developerserver'
    class Result:
        SUCCESS = 'success'
        FAILURE = 'failure'
    