from base.message_format import MessageFormat

class Formats:
    MESSAGE = MessageFormat({
        'message_id': str, 
        'message_type': str, 
        'data': dict
    })
    """
    message_id: the id of request, usually generated by uuid4.\n
    message_type: the type of message. See Words\n
    data: keys are parameters, values are corresponding values.\n
    """

    # REQUEST = MessageFormat({
    #     'message_id': str, 
    #     'request_command': str, 
    #     'data': dict
    # })
    # """
    # message_id: the id of request, usually generated by uuid4.\n
    # request_command: the command of request. See Words\n
    # data: keys are parameters, values are corresponding values.\n
    # """

    # RESPONSE = MessageFormat({
    #     'response_id': str, 
    #     'response_type': str, 
    #     'responding_id': str, 
    #     'data': dict
    # })
    # """
    # response_id: the id of request you are responding.\n
    # request_command: the command of request. See Words\n
    # data: keys are parameters, values are corresponding values.\n
    # """

class Words:
    class MessageType:
        REQUEST = 'request'
        RESPONSE = 'response'
        EVENT = 'event'
        HANDSHAKE = 'handshake'
    class Command:
        LOGIN = 'login'
    class DataKeys:
        PARAMS = 'params'
        class Handshake:
            ROLE = 'role'
        class Response:
            RESPONDING_ID = 'responding_id'
            RESULT = 'result'
        class Request:
            COMMAND = 'command'
    class ParamKeys:
        class Login:
            USERNAME = 'username'
            PASSWORD = 'password'
        class Failure:
            REASON = 'reason'
    class Roles:
        PLAYER = 'player'
    class Result:
        SUCCESS = 'success'
        FAILURE = 'failure'
        