from base.message_format import MessageFormat

class Formats:
    MESSAGE = MessageFormat({
        'message_id': str, 
        'message_type': str, 
        'data': dict
    })
    """
    message_id: the id of request, usually generated by uuid4.\n
    message_type: the type of message. See Words\n
    data: keys are parameters, values are corresponding values.\n
    """

class Words:
    class MessageType:
        REQUEST = 'request'
        RESPONSE = 'response'
        EVENT = 'event'
        HANDSHAKE = 'handshake'
        HEARTBEAT = 'heartbeat'
    class Command:
        SYNC_LOBBY_STATUS = 'sync_lobby_status'
        GET_PLAYER_ROOM_STATUS = 'get_player_room_status'
        LOGIN = 'login'
        LOGOUT = 'logout'
        REGISTER = 'register'
        EXIT = 'exit'
        UPLOAD_START = 'upload_start'
        UPLOAD_END = 'upload_end'
    class EventName:
        PLAYER_ONLINE = 'player_online'
        PLAYER_OFFLINE = 'player_offline'
    class DataKeys:
        PARAMS = 'params'
        class Handshake:
            ROLE = 'role'
        class Response:
            RESPONDING_ID = 'responding_id'
            RESULT = 'result'
        class Request:
            COMMAND = 'command'
        class Event:
            EVENT_NAME = 'event_name'
    class ParamKeys:
        class Login:
            USERNAME = 'username'
            PASSWORD = 'password'
        class Logout:
            USERNAME = 'username'
        class Register:
            USERNAME = 'username'
            PASSWORD = 'password'
        class Failure:
            REASON = 'reason'
        class PlayerOnline:
            PLAYER_NAME = 'player_name'
        class PlayerOffline:
            PLAYER_NAME = 'player_name'
        class LobbyStatus:
            ONLINE_PLAYERS = 'online_players'
            ROOMS = 'rooms'
    class Roles:
        PLAYER = 'player'
        DEVELOPER = 'developer'
        LOBBYSERVER = 'lobbyserver'
        DEVELOPERSERVER = 'developerserver'
    class Result:
        SUCCESS = 'success'
        FAILURE = 'failure'
        